apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: training
  name: training-job1
  labels:
    k8s-app: fluentd-logging
spec:
  selector:
    matchLabels:
      name: fluentd-elasticsearch
  template:
    metadata:
      labels:
        name: fluentd-elasticsearch
    spec:
      nodeSelector:
        NODE_RANK: "0"
      hostNetwork: true
      containers:
      - name: clickbait-distilbert
        image: master:443/clickbait-detector:amd
        imagePullPolicy: Always
        env:
          - name: GLOO_SOCKET_IFNAME
            value: ens5
        volumeMounts:
        - name: data-volume
          mountPath: /ClickbaitDetector/data
        - name: logs-volume
          mountPath: /ClickbaitDetector/logs
        - name: config
          mountPath: /ClickbaitDetector/config.json
        - name: certs
          mountPath: /etc/docker/certs.d
        command: ["torchrun"]
        args: ["--nproc_per_node=2","--nnodes=2","--node_rank=0","--rdzv_id=456","--rdzv_backend=c10d","--rdzv_endpoint=172.31.97.187:12357","--master_addr=172.31.97.187","--master_port=12356","train.py"]
      volumes:
      - name: data-volume
        hostPath:
          path: /home/cloud_user/clickbait/ClickbaitDetector/data
      - name: logs-volume
        hostPath:
          path: /home/cloud_user/clickbait/ClickbaitDetector/logs
      - name: config
        hostPath:
          path: /home/cloud_user/clickbait/ClickbaitDetector/config.json
      - name: certs
        hostPath:
          path: /etc/docker/certs.d
      imagePullSecrets:
      - name: private-registry-secret